name: Notify on Push

on:
  push:
    branches:
      - main

jobs:
  notify_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Notify about Push
        if: github.event_name == 'push'
        run: |
          echo "Nueva actualización del Manual para supervivientes"
          echo "Enlace de la página: https://xzackyx.github.io/Manual-para-supervivientes/"
