name: Notify on Push

on:
  push:
    branches:
      - main

jobs:
  notify_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        if: github.event_name == 'push'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "content": "Nueva actualización del Manual para supervivientes\nEnlace de la página: https://xzackyx.github.io/Manual-para-supervivientes/"
          }' $DISCORD_WEBHOOK_URL
